all: task4

task4: task4.o
	gcc -g -m32 -Wall -fno-pie -fno-stack-protector -o task4 task4.o

task4.o: task4.c task1
	gcc -g -m32 -Wall -fno-pie -fno-stack-protector -c -o task4.o task4.c

task1: task1.o
	gcc -g -m32 -Wall -fno-pie -fno-stack-protector -o task1 task1.o

task1.o: task1.c
	gcc -g -m32 -Wall -fno-pie -fno-stack-protector -c -o task1.o task1.c

	
.PHONY: clean
clean:
	rm -f *.o task4 task1
